### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by beiske** [elastic/securemock#1]
It is about time we release this, it's been stable for a long time and multiple projects depend on it. Need to make a release as is

**Comment by beiske** [comment]
@dadoonet Are there any particular repositories or other settings that should be added in the pom before we release this?

**Comment by dadoonet** [comment]
We need to fix:
- https://github.com/elastic/securemock/blob/master/pom.xml#L27-L29 (wrong urls)
- https://github.com/elastic/securemock/blob/master/pom.xml#L38-L44 (i don't think we need that)

Otherwise, I think it's ok to publish on sonatype (default)

**Comment by rmuir** [comment]
I just fixed the terrible "clean hack" too: https://github.com/elastic/securemock/commit/d02a39002f7502015aa829885cc8ec6ffb497e36

**Comment by beiske** [comment]
It is released: http://search.maven.org/#artifactdetails|org.elasticsearch|securemock|1.0|jar
